---
- hosts: servers
  vars_files:
    - vars.yml
    # - @vault.yml
  gather_facts: true
  become: true
  become_user: "{{ project_name }}"
  roles:
    - common
  tasks:

  - cronvar:
      name: MAILTO
      value: "{{ cron_email }}"
      user: "{{ project_name }}"

  - cron:
      name: "Check images"
      minute: "*/15"
      job: "echo 'select i.id from images_image i left outer join candidates_imageextra ie on ie.base_id = i.id where ie.id IS NULL order by i.id;' | psql -q -t ynr | sed '/^$/d'"

  - cron:
      name: "Create CSVs"
      minute: "15,45"
      job: "nice -n 19 ionice -c 3 /usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py candidates_create_csv --site-base-url https://candidates.democracyclub.org.uk {{project_root}}/media_root/candidates"


  - cron:
      name: "For election night, generate the 2017 GE CSV file more frequently"
      minute: "*/5"
      job: "nice -n 19 ionice -c 3 /usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py candidates_create_csv --site-base-url https://candidates.democracyclub.org.uk --election parl.2017-06-08 {{project_root}}/media_root/candidates"
      disabled: yes


  - cron:
      name: "Create nightly CSVs for archival purposes"
      minute: "30"
      hour: "00"
      job: "nice -n 19 ionice -c 3 /usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py candidates_create_csv --site-base-url https://candidates.democracyclub.org.uk --election parl.2017-06-08 {{project_root}}/media_root/csv-archives/candidates-`date +\\%Y\\%m\\%d`"

  - cron:
      name: "Detect faces"
      minute: "30,04,19"
      job: "nice -n 19 ionice -c 3 /usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py moderation_queue_detect_faces_in_queued_images"
      disabled: no
    when: deploy_env == "production"

  - cron:
      name: "Backup images"
      minute: "45"
      job: "/usr/local/bin/output-on-error {{project_root}}/backup_images.sh > /dev/null"
    when: deploy_env == "production"

  - cron:
      name: "Import elections from EE"
      minute: "06"
      job: "/usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py uk_create_elections_from_every_election"

  - cron:
      name: "Update Twitter usernames"
      minute: "06"
      hour: "01"
      job: "/usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py candidates_update_twitter_usernames"
    when: deploy_env == "production"

  - cron:
      name: "Update parties from EC"
      minute: "06"
      hour: "02"
      job: "/usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py uk_update_parties_from_ec_data"

  - cron:
      name: "Add Twitter images to image queue"
      minute: "06"
      hour: "03"
      job: "/usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py candidates_add_twitter_images_to_queue"
    when: deploy_env == "production"

  - cron:
      name: "Build static person pages"
      minute: "10"
      hour: 1 # For non-election times
      job: "/usr/local/bin/output-on-error {{project_root}}/env/bin/python {{project_root}}/code/manage.py candidates_cache_api_to_directory {{django_media_root}}/cached-api https://candidates.democracyclub.org.uk/media/cached-api --prune"
    when: deploy_env == "production"
